title: Hello World
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Me"
  email: "someone@somewebsite.somedomain"
  url: "https:/wojtekgoo.github.io"

baseurl: ''

github:
  username: wojtekgoo             # change to your github username

twitter:
  username: twitter_username            # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Wojtek
  email: wojtekgoo@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/wojtekgoo       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/wojtekgusztyla/

<<<<<<< HEAD
source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  # posts 
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sidebar: navigation
  
  # pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: navigation

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
=======



>>>>>>> f5b9fe68e18583aad7770770b8a1fa695d83e5f4

# Custom variables
owner : "Me"
year : "2021"
