name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          #bundler-cache: true

      - name: Bundle Install
        run: |
          bundle config path ${{ env.GEMS_PATH }}
          bundle install --jobs 4 --retry 3

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "BASE_URL=$baseurl" >> $GITHUB_ENV
          fi

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b
          if [[ -n $SPEC_TEST ]]; then
            # Bypass the defects of htmlproofer
            bundle exec jekyll b -b "" -d "$SPEC_TEST"
          fi

      - name: Init Site
        run: |
          if [[ -n $SPEC_TEST ]]; then
            bash tools/init.sh -d "$SPEC_TEST"
          else
            bash tools/init.sh
          fi

      - name: Test Site
        run: |
          if [[ -n $SPEC_TEST ]]; then
            bash tools/test.sh -d "$SPEC_TEST"
          else
            bash tools/test.sh
          fi
          
      - name: Deploy
        run: |
          bash tools/deploy.sh